### ISSUE TITLE
Corregir ruta hacia la base de datos

### ISSUE THREAD

**Issue by gacsnic** [jugnicaragua/PICO#37]
La ruta proporcionada por un enlace simbólico, proporciona una ruta absoluta en un equipó especifico provocando un error al ejecutar la aplicación en otra equipo.

**Comment by yessermiranda13** [comment]
Según reviso esa configuración proviene de hibernate.
[https://github.com/jugnicaragua/PICO/blob/develop/src/main/resources/hibernate.cfg.xml](hibernate.cfg.xml)

Habría que buscar una manera de solicitar el directorio donde se va a guardar o seleccionar uno que sea accesible desde la aplicación. No se si es necesario, pero como es sqlite no se en que directorio se podría guardar. Para maven que utiliza el directorio resources, sería una opción.
