### ISSUE TITLE
Documentancion del codigo

### ISSUE THREAD

**Issue by gacsnic** [jugnicaragua/PICO#40]
Se debe de documentar el codigo, todo los que estén desarrollando deben de documentar el código que generen. tomando en consideración que la documentación debe ser orientada a personas con poco conocimiento del lenguaje Java.

El encargado de este issues debe de supervisar que el codigo proporcionado esta bien documentado antes de aceptar el PR.

**Comment by berroteran** [comment]
ok, pero esto debe estar en la documentación, no en un Issue.
