### ISSUE TITLE
Mantenimiento de vista Acerca de

### ISSUE THREAD

**Issue by gacsnic** [jugnicaragua/PICO#41]
Con este issues se le dará mantenimiento a la vista Acerca de, entendiendo por mantenimiento agregar colaboradores a la lista, cambiar imagen presentada en la vista, cambiar color de letra y fondo de la vista.

Para cada mantenimiento se  creara una rama en el repositorio local, el nombre de la rama tendra que describir el mantenimiento que se realizara y se le agregara al nombre el numero de este issues

**Comment by berroteran** [comment]
No, asi  no funciona, 
asi no es como se usan los tickets, 

Tampoco se crearan ramas... cada persona trabaja en su equipo y luego se hacen Pull Request.

**Comment by gacsnic** [comment]
> No, asi no funciona,
> asi no es como se usan los tickets,
> 
> Tampoco se crearan ramas... cada persona trabaja en su equipo y luego se hacen Pull Request.
@berroteran 
a como describes el procedimiento, la rama feature/55 no existiria y los cambios que contiene la feature/55 estuvieran en la rama develop. recuerda que no has tenido tiempo para retro alimentar la dirección a seguir y si cada colaborador de lo que el considere mejor hace directo un PR a develop , la base de PICO se pudieran perder.
