### ISSUE TITLE
[TASK] - Modificar la clase org.jugni.apps.pico.modelos.Identificador

### ISSUE THREAD

**Issue by jselvamadrigal** [jugnicaragua/PICO#46]
Las entidades deben de tener identificadores propios estos pueden ser de tipo simple o compuesto, por lo tanto la clase Identificador no cumple con ese requisito y su utilidad no esta definida claramente.

La clase también define el **GeneratedValue** con una estrategia de **SEQUENCE** lo que provoca que todas las entidades que la hereden tengan un identificador no continuo.

Al remover la clase se modificaran los modelos que extiendan de dicha clase y donde exista una referencia a la misma.

**Comment by gacsnic** [comment]
hasta el dia de hoy no se había planteado identificadores de tipo compuesto, se tendría que considerar si es necesario establecer en las entidades identificadores compuesto.

La estrategia de GeneratedValue se puede sobrescribir en cada identidad o modificar la estrategia de la clase padre.

**Comment by berroteran** [comment]
este issue se cierra por falta de coherencia. 

La descripción no tiene nada de que ver en el titulo, 
Lo que describen en el ticket ya se está tratando en otro issue. 

recuerden un Ticket por Issue, una sola característica o un solo problema.
