### ISSUE TITLE
[REFACTOR] - Seguridad, refactorización y restructuración de código

### ISSUE THREAD

**Issue by jselvamadrigal** [jugnicaragua/PICO#55]
Actualmente el proyecto cuenta con falta de buenas practicas de código, como son respectar el naming convention del lenguaje Java, lenguaje estándar en la industria para la declaración de los nombres de objetos, métodos y clases. El uso de muchas variables y/o métodos globales innecesarios.

El proyecto carece de una estructura solida para la inclusión de una sesión global definida en un módulo de seguridad.

Mi propuesta es refactorizar el código, cumpliendo con naming convention  del lenguaje Java, reestructurar el árbol de paquete

org.jugni.apps.pico  
-data  
-security  
-ui

Agregar la estructura básica del módulo de seguridad, y corregir el manejo de la vista principal y menús.

**Comment by gacsnic** [comment]
@jselvamadrigal  
Por que no solo renombrar paquetes?

**Comment by gacsnic** [comment]
@jselvamadrigal 
La otra consulta pendiente es la de la clase PicoApplication, el constructor es publico y el diseño de esta clase es para aplicar el patrón singleton(Se que no la creaste tu que solo renombraste y hiciste cambio menores), por lo que propongo cambiar el constructor a privado. Pero me comentabas por slack de no abusar de sigleton por las pruebas unitarias, mi consulta es como afecta en las pruebas unitarias si tiene un ejemplo te lo agradeceria?

**Comment by jselvamadrigal** [comment]
> 2\. s
1. @gacsnic la estructura se encuentra mas ordenada y es mas fácil para un principiante encontrar las cosas.

2. @gacsnic Por que es un modulo sensible, sus clases aunque sean pojo no deberían de declararse en un módulo aparte.

**Comment by jselvamadrigal** [comment]
> @jselvamadrigal
> La otra consulta pendiente es la de la clase PicoApplication, el constructor es publico y el diseño de esta clase es para aplicar el patrón singleton(Se que no la creaste tu que solo renombraste y hiciste cambio menores), por lo que propongo cambiar el constructor a privado. Pero me comentabas por slack de no abusar de sigleton por las pruebas unitarias, mi consulta es como afecta en las pruebas unitarias si tiene un ejemplo te lo agradeceria?

No recomiendo utilizar el "patron" singlenton ya que es una manera "bonita" de hacer uso de una mala practica de "variables globales", el singlenton no es más que eso una variable global, mas bien recomendaría ir sustituyendo este "patron"

https://www.youtube.com/watch?v=-FRm3VPhseI

**Comment by gacsnic** [comment]
> > @jselvamadrigal
> > La otra consulta pendiente es la de la clase PicoApplication, el constructor es publico y el diseño de esta clase es para aplicar el patrón singleton(Se que no la creaste tu que solo renombraste y hiciste cambio menores), por lo que propongo cambiar el constructor a privado. Pero me comentabas por slack de no abusar de sigleton por las pruebas unitarias, mi consulta es como afecta en las pruebas unitarias si tiene un ejemplo te lo agradeceria?
> 
> No recomiendo utilizar el "patron" singlenton ya que es una manera "bonita" de hacer uso de una mala practica de "variables globales", el singlenton no es más que eso una variable global, mas bien recomendaría ir sustituyendo este "patron"
> 
> https://www.youtube.com/watch?v=-FRm3VPhseI
@jselvamadrigal 
Entendido, mi aporte a al issue [https://www.davidtanzer.net/david%27s%20blog/2016/03/14/6-reasons-why-you-should-avoid-singletons.html](url)

**Comment by luchonetvv** [comment]
Recapitulando @gacsnic @jselvamadrigal recuerden llevar acá el hilo con respecto al Issue, gracias.

**Comment by gacsnic** [comment]
> > 2. s
> 
>     1. @gacsnic la estructura se encuentra mas ordenada y es mas fácil para un principiante encontrar las cosas.
> 
>     2. @gacsnic Por que es un modulo sensible, sus clases aunque sean pojo no deberían de declararse en un módulo aparte.

@jselvamadrigal 

Para el primer punto, por tu respuesta recomiendo que lo pongamos a votación, lo recomiendo así, por que tu respuesta hace  ver como que esta basada en tu percepción, si tienes documentación de la estructura que propones que nos puedas facilitar, para que proceda el PR.      

El punto numero dos, me confundí o  te confundiste? " aunque sean pojo **_no_** deberían de declararse en un módulo aparte.".

**Comment by jselvamadrigal** [comment]
@gacsnic 2. No fui claro, quise decir que aunque sean pojos (entidades), no es recomendable dejarlos en un modulo separado al modulo de seguridad, ya que su  contexto es solo para el manejo de seguridad, ese seria su scope.

**Comment by gacsnic** [comment]
> Actualmente el proyecto cuenta con falta de buenas practicas de código, como son respectar el naming convention del lenguaje Java, lenguaje estándar en la industria para la declaración de los nombres de objetos, métodos y clases. El uso de muchas variables y/o métodos globales innecesarios.
> 
> El proyecto carece de una estructura solida para la inclusión de una sesión global definida en un módulo de seguridad.
> 
> Mi propuesta es refactorizar el código, cumpliendo con naming convention del lenguaje Java, reestructurar el árbol de paquete
> 
> org.jugni.apps.pico
> -data
> -security
> -ui
> 
> Agregar la estructura básica del módulo de seguridad, y corregir el manejo de la vista principal y menús.

@jselvamadrigal 
Tomando en cuenta los objetivos del proyecto, doy un pequeño aporte a tu propuesta, aunque por tu experiencia no lo mires necesaria, recuerda que la enseñanza en la universidades locales esta basada en MVC y para rematar lo que enseñan de ingles es muy poco o nulo.   

data -> A como su nombre hace referencia, este paquete contendrá todo lo referente a la persistencia de datos, los paquetes dao y model quedan como sub-paquetes del paquete data.
ui -> sustituye al paquete view, Este paquete contendrá todo lo referente a las vista lo que interactúa directamente con el usuario, [https://blog.acantu.com/que-es-ui-intefaz/](url)      
security-> Este paquete contendrá todo lo referente a la seguridad. 

Considerando que no se hizo mas aporte (slack,github y telegram) de los demás colaboradores, referente al feature que propones, de mi parte diría que podríamos proceder .   @luchonetvv  tu VoBo.

**Comment by luchonetvv** [comment]
@gacsnic @jselvamadrigal me parece que la forma de organizar por módulo hace más sencillo de ubicarse en el **Proyecto** inclusive viéndolo desde la perspectiva de explorador de carpetas, entonces dejando "security" como módulo me parece bien, "ui" casi que es una práctica común inclusive en móvil, creo que @armalagon en el refactor que hizo lo dejó así también, la capa de datos en este caso "data" se sobre entiende para que es, puede ser que no sea algo intuitivo determinar que hay dentro lo que si es seguro que tiene que ver con los datos en mi caso podría intuir que son cosas como dao, entities, etc, ahora puede ser que no sea necesario sacar a la raíz del **Proyecto** el "dao" o "entities" porque me parece que más adelante ese paquete de "data" podría gestionarse como módulo y convertirse en una dependencia del **Proyecto PICO** y probablemente "security" podría ser otro módulo y convertirse en dependencia del **Proyecto** también, esto pensando en modularizar el **Proyecto**.

Lo otro es que no he revisado el **Proyecto** no sé si hay una capa "controller" para cumplir con el patrón **MVC**, recordemos que estos patrones sobre todo **MVC** que es bastante viejo en el sentido de su aparición y uso, con los frameworks de hoy en día se abstrae mucha complejidad y conceptos, por ende separar las capas por los componentes que propone **MVC** no se de, de manera natural sería revisar bien esa parte, en la [Wikipedia](https://es.wikipedia.org/wiki/Modelo%E2%80%93vista%E2%80%93controlador) con respecto a **MVC** lo mencionan.

En resumen pienso que agrupar por módulos sería mejor pensando en modularizar el **Proyecto** esto por el motivo que saquemos algún módulo para convertirlo en dependencia del **Proyecto** y a como lo veo agrupado me parece bien, de igual manera todo esto debe quedar documentado cualquier decisión que se tome para que cualquiera pueda tomar el **Proyecto** y continuar con el Desarrollo.

**Comment by berroteran** [comment]
Dedicaré un poco mas de tiempo a este ticket, ya que veo que tienen MUCHA INFORMACIÓN. 

** les recuerdo  **mantener los tickets sencillos**, en relación de los temas  o tópicos a tratar. Un Topico por Issue.

**Comment by berroteran** [comment]
con respecto a los paquetes.... 
Recapitulando.... 

1) PICO la version desktop,  no usará otro frameWork parte de Hibernate, 
2) Aunque aplicar patrones sea verbose, así se hará, el objetivo, es luego compararlo con pico-web
3) Todas aplicaciones proyectos de Jug nicaragua deben empezar con el siguiente paquete. 
**org.jugnicaragua.app**

partiendo de eso, dado que el objetivo es reforzar la percepcion del modelo MVC, se mantendran las carpetas: 
- Modelo (para los modelos) 
- Vista  (para la interfaz gráfica, indicando que es la  vista) en pico web, usaremos UI, 
- Controlador. 
- DAO ( para aplicar el patrón DAO)  se mantiene. 

org.jugnicaragua.app.PICO
......................................... - modelo
......................................... - vista
............................................... - utils
......................................... - controles
......................................... - servicios
......................................... - utils


si bien la seguridad es un punto importante, no veo porque debe estar en paquete aparte, la seguridad de PICO es minima, no utiliza encriptación o tareas recurrentes, se puede agregar despues, depende de como fluya el proyecto. 

Con respecto al SingleTon, ya tuve una discusión con Armando al respecto, me mencióno varias cosas que se pueden manejar, para evitar el uso de SigleTon, sin embargo, de implementarlo  lo haremos bien, para el control de instancias de ventanas, se usara mapeo en la ventanaPrincipal, ya que es responsabilidad de la clase VentanaPricipal gestionar las intancias de las ventanas que maneja. 




** Cada  justificación o explicación deberá  ponerse en la clase Package.java

**Comment by jselvamadrigal** [comment]
@berroteran lo que se intenta lograr con la distribución de paquetes actual, es la modularización del proyecto, con la finalidad de compartir módulos importantes entre distintos proyectos como son PICO y PICO web.

**Comment by berroteran** [comment]
si @jselvamadrigal , 
Recuerda que la parte de la modulos se hara para PICO  web, en :
- Pico CORE
y
- PICO web dependiendo de Pico web.
